name = "TinyAD"
uuid = "673e833b-f517-4aee-a9da-c45bac71b507"
authors = ["Yusheng Zhao<yushengzhao2020@outlook.com>"]
version = "0.1.0"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[compat]
Enzyme = "0.11"
julia = "1.8"
